### ISSUE TITLE
Ability to minimize/hide gifs

### ISSUE THREAD

**Issue by patrickgalbraith** [moussetc/mattermost-plugin-giphy#12]
Would be great to have the ability to collapse/minimize/hide gifs.

How it works in slack:
![image](https://user-images.githubusercontent.com/811945/47892706-249e6600-dea9-11e8-8bbf-2c4f19a63512.png)

How it works when using the gfycat integration
![image](https://user-images.githubusercontent.com/811945/47892698-181a0d80-dea9-11e8-9548-7e6795c3a631.png)

**Comment by patrickgalbraith** [comment]
Thanks for following this up.

Hopefully mattermost follow through.

-Patrick

**Comment by hughes** [comment]
Looks like the mattermost ticket was closed without addressing this particular issue.

**Comment by corporalaris** [comment]
Either this needs to get worked here or a better ticket needs to get raised against Mattermost so they don't get confused by the wording.

**Comment by fritojay** [comment]
@corporalaris I forked it and did the URL integration instead. It's not ideal, but it works for my friends and I.

**Comment by hanzei** [comment]
https://github.com/mattermost/mattermost-webapp/pull/3639 should have fixed this issue. Would you mind trying to repo it with >= MM 5.18

**Comment by hughes** [comment]
> [mattermost/mattermost-webapp#3639](https://github.com/mattermost/mattermost-webapp/pull/3639) should have fixed this issue. Would you mind trying to repo it with >= MM 5.18?

The linked PR did nothing to address minimizing/hiding gifs or markdown images. It now just opens them in popout modals when clicked, and no changes have been made to the minimization feature.

**Comment by moussetc** [comment]
@Hanzei The issue was not solved, as hughes says. Example on the community.mattermost.com (currently at 2.20.1) server, with first a raw url (displayed with the minimize button) and second an inline image without the button:
![image](https://user-images.githubusercontent.com/8834237/75191048-e68a1d00-5751-11ea-89cc-6cf3a673b515.png)
It's more a feature request than a bug, can I still open an issue on mattermost/mattermost-server or should we open a new topic on http://www.mattermost.org/feature-requests/ ?

**Comment by hanzei** [comment]
@moussetc Got it :+1: I think a topic on http://www.mattermost.org/feature-requests/ would be the right place

**Comment by moussetc** [comment]
I posted the following [feature request](https://mattermost.uservoice.com/forums/306457-general/suggestions/40030456-button-to-minimize-inline-images-ex-gifs-plugin) so if you you're interested in this feature, go vote for it (and look around for others interesting requests, there aplenty).

**Comment by esethna** [comment]
@moussetc @hughes @patrickgalbraith @corporalaris can I ask your help in clarifying the problem you're trying to solve?

A) Is it that you'd like to be able to collapse GIFs (because currently the GIFs are already collapsible
![image](https://user-images.githubusercontent.com/14333569/80411049-6468c280-8880-11ea-8e34-3b89e63d5109.png)

B) Is it that the URL for the GIF is not human readable and thus is distracting?
![image](https://user-images.githubusercontent.com/14333569/80411214-a4c84080-8880-11ea-8cc6-710997f0cf49.png)

With the approach taken in this PR https://github.com/mattermost/mattermost-webapp/pull/5396, GIFs will no longer be collapsible since in-line markdown images are not collapsible. 

![image](https://user-images.githubusercontent.com/14333569/80411285-ccb7a400-8880-11ea-9b6e-6318d861d1ad.png)

**Comment by moussetc** [comment]
@esethna Sure!

This issue is not about the integrated Gfycat picker or about copy-pasting an URL as a message, it's about the Mattermost GIF command plugin, of which here's a sample :
![demo](https://raw.githubusercontent.com/moussetc/mattermost-plugin-giphy/master/assets/demo_gif.png).

When developing this plugin, I chose to display the GIF as an inline image, _because_ I disliked having a raw URL displayed (so I support whole heartedly the PR you're linking to !) ; but inline images are not collapsible, as you can see in the picture above. This is the issue bbodenmiller is referring to. It was also cross-posted on the [Mattermost uservoice forum](https://mattermost.uservoice.com/forums/306457-general/suggestions/40030456-button-to-minimize-inline-images-ex-gifs-plugin).

**Comment by hughes** [comment]
More generally, there is no way to collapse gifs or other images shown in markdown content. Since the `/gif` command renders the image with markdown syntax (`![](https://gif/url)`) there is no wasy to collapse it.

**Comment by esethna** [comment]
Got it, thanks for the clarification. @bbodenmiller given the above feedback, I'd propose we close the PR submitted https://github.com/mattermost/mattermost-webapp/pull/5396, given it removes the collapse GIF ability. 

However, I agree seeing the full link is ugly and we should look into how we can improve that or make inline images collapsible. For those following this thread, if we could figure out the user experience around collapsing in-line images, would that be the ideal solution here?

**Comment by gigawhitlocks** [comment]
> For those following this thread, if we could figure out the user experience around collapsing in-line images, would that be the ideal solution here?

I'll let the other users in this thread speak for themselves but the users on my server have complained about the inability to collapse in-line images and so at least on behalf of _my_ users, the answer to your question @esethna is a resounding "yes"

**Comment by ohporter** [comment]
> if we could figure out the user experience around collapsing in-line images, would that be the ideal solution here?

My users are just begging for a collapsible image by any means possible. Since they complain about everything, I'm sure they'd complain about having the full URL on their tenor-sourced gifs...but that would be better that no collapsing. Would it be possible to add a configuration option to render them as an embedded image versus default of inline image. It seems like there's no action upstream on https://mattermost.atlassian.net/browse/MM-12290

**Comment by crbanman** [comment]
> My users are just begging for a collapsible image by any means possible. 

I'm pretty much in the same boat. A configuration option to use URLs instead of inline images would be great to have. At least until MM allows collapsible inline images.

Worst case I'll either have to disable the plugin until MM allows collapsing inline images or fork it to add the option.

**Comment by crbanman** [comment]
@moussetc thanks for working on this. It will reduce a lot of flak that I'm getting from users 😅

**Comment by JFCG4mer** [comment]
Thank you @esethna and @moussetc for your time and attention to this. It would certainly increase adoption of this plugin to have the ability to collapse inline images (in MM) or a configurable workaround for users that prefer to disable it somehow.  Thanks again!

**Comment by moussetc** [comment]
There's now an option to display the GIF as URL, with the collapsible image preview :tada: 

This option appears in version 1.4.0+ of the plugin, which is now available as a pre-release on Github and will be available in the Mattermost plugin marketplace after the review and tests process.

I'm closing this issue, as for now we can only wait for the implementation of the [Mattermost issue](https://mattermost.atlassian.net/browse/MM-12290) to enable embedded image collapse :slightly_smiling_face:

**Comment by moussetc** [comment]
As embedded image collapse [has been implemented](https://mattermost.atlassian.net/browse/MM-12290) by Mattermost in V5.35, I'm unpinning this issue and will plan to remove the option to display raw URL, as it's not needed anymore.
