### ISSUE TITLE
Proxy support ?

### ISSUE THREAD

**Issue by demogorgonz** [moussetc/mattermost-plugin-giphy#13]
```
{"level":"error","ts":1551353481.0480194,"caller":"web/context.go:60","msg":"Unable to get GIF URL","path":"/api/v4/commands/execute","request_id":"ceccq53m7bgx3desddbzpqttto","ip_addr":"X.X.X.X","user_id":"5x1ppqpetjnd8gxr4jgbnp8hjy","method":"POST","err_where":"Giphy Plugin","http_code":400,"err_details":"Get http://api.giphy.com/v1/gifs/translate?api_key=MYKEY=+test&lang=en: dial tcp 151.101.122.2:80: connect: connection refused"}

```

Is there any advice regarding running this behind corporate proxy(squid) ?

Mattermost Version: 5.5.0
OS: Ubuntu

I have added already environment variables for outbound connection : [MM docs](https://docs.mattermost.com/install/outbound-proxy.html)

**Comment by hathagat** [comment]
Same issue here. The opportunity to make gifs work behind a proxy would be great!

**Comment by schdief** [comment]
tried to set up this plugin and failed at the same point:
Unable to get GIF URL

**Comment by moussetc** [comment]
I might not be able to looking into it shortly, but in the meantime, could you all confirm that:
- your Mattermost server is behind a proxy, setup with HTTP_PROXY/HTTPS_PROXY env variables
- when running the URL of the `error_details` in your error log in a browser also behind the corporate proxy, you don't get any error

Thanks

**Comment by hathagat** [comment]
Thank you for looking into it!

The server itself cannot access the internet. But if I would have access to the servers shell, it would be possible to set up proxy env variables to get internet access.
Accessing the URL in a browser works because the browser uses the corporate proxy, yes.

For my use case it would be perfect if there would be some kind of proxy in the plugins settings like `http_proxy=http://192.168.0.172:3128` for example.

Additionally, lots of corporate proxies need credentials to be submitted as well. So for that use case something like `http_proxy=myuser:mypass@http://192.168.0.172:3128` would be necessary, I believe.

**Comment by moussetc** [comment]
I still can't work on this issue but yeah, setting the environment variables [as documented here](https://docs.mattermost.com/install/outbound-proxy.html?highlight=proxy) is a necessary first step anyway. You're right about needing to add user/password if the proxy need them.

(Proxy configuration shouldn't be done at plugin level because if would mean having to configure each and every plugin, whereas if done at the mattermost level, all plugins should benefit from it.)

@hathagat Could you try setting your variables and see it it works better ?
@schdief Could you post the actual error line from your logs, please, it should contain a more detailed error message.

**Comment by moussetc** [comment]
I'll be closing this issue in a few days if there are no answers ;)
