### ISSUE TITLE
Integrate with built in GFYCAT API?

### ISSUE THREAD

**Issue by uhlhosting** [moussetc/mattermost-plugin-giphy#17]
Maybe a solution to hook up to the MM Api for GIF settings, could bring some nice improvements.

**Comment by moussetc** [comment]
Interesting, what specific improvements are you thinking about?
I see at least the possibility to add Gfycat as a GIF provider instead of Giphy - needs only one API key and more coherence between the proposed GIFs if users use both the plugin and the integrated GUI, but do you have anything else in mind? 
Though as far as a quick looks tells me, whereas the plugin does have access to the Gfycat settings, the "native" calls to Gfycat are actually made directly from the client, so that limits the possible reuse.

**Comment by uhlhosting** [comment]
@moussetc was thinking maybe you can hook up somehow to the GIF (Beta) feature already existing, and that would bring it to slash / cmd also.

**Comment by moussetc** [comment]
I'm still not sure what behavior you were thinking of, but integration with the official GIF feature (such as opening the GIF menu in the GUI as a reaction to as slash command) doesn't seem possible anyway.
However, there is now in the plugin latest versions the possibility to use Gfycat as a gif provider rather than Giphy. Hope that's what you hoped for.

**Comment by moussetc** [comment]
This ticket is closed due to inactivity for more than 6 months.
