### ISSUE TITLE
Toggle X.509 certificate check on known URLs

### ISSUE THREAD

**Issue by jprusch** [moussetc/mattermost-plugin-giphy#33]
Hi,
right now the static URLs of gfycat & giffy are checked for on each call. We do some deep inspection of the content with our own X509 infrastructure to filter our malicious content.
It would be great to have the option to switch X509 certificate checks off.
Example:
`2020-07-24T09:33:23.098+0200    error   mlog/log.go:175 Error calling the GfyCat search API     {"path": "/api/v4/commands/execute", "request_id": "123456789", "ip_addr": "1.2.3.4", "user_id": "987654321", "method": "POST", "err_where": "GIF commands", "http_code": 400, "err_details": "Get \"https://api.gfycat.com/v1/gfycats/search?count=1&search_text=+master\": x509: certificate signed by unknown authority"}`
Thx,
JP

**Comment by moussetc** [comment]
Hi,
Given the error message, the inspection actually replace the original certificate by another certificate issued by a custom CA, it that right ?

If yes, have you tried the following:
- Adding your custom CA cert  to the Mattermost server (as described on [this thread](https://forum.mattermost.org/t/where-does-mattermost-server-take-its-certificate-trust-from/7887))
- Enabling the Mattermost option [Enable Insecure Outgoing Connexions](https://forum.mattermost.org/t/where-does-mattermost-server-take-its-certificate-trust-from/7887)

?

If all external certificates are replaced by the infrastructure, other MM plugins/interactions would impacted: rather than adding an unsecure option at plugin level, it'd be better to fix it server side.

**Comment by jprusch** [comment]
Thx, makes sense. Will try to add the custom CA.
