### ISSUE TITLE
Some images not rendering on Mattermost servers using subpath

### ISSUE THREAD

**Issue by mickmister** [moussetc/mattermost-plugin-giphy#50]
This issue was originally brought up in https://github.com/mattermost/mattermost-server/issues/19656. Some plugins, including this plugin, may need to be updated to support servers hosted on a subpath.

Making sure we take into account the server's `SiteURL` will make sure we use the correct path. Please see this PR for a similar fix https://github.com/mattermost/mattermost-plugin-github/pull/459

**Comment by moussetc** [comment]
Thanks for the report. 

The linked PR is not wholly pertinent, as it's frontend and the Gif plugin is completely on the backend side.

I'm having trouble reproducing the issue - I'm not familiar with Nginx and I think I messed up my configuration with docker/docker-compose (which I use to start Ngxinx+Mattermost-preview) because I can't even load the plugin package via the redirected url, only with the direct localhost:8065 url.

I think the fix would be to replace https://github.com/moussetc/mattermost-plugin-giphy/blob/a81cdfc0202ab66427976652fb163a2b1bf37939/server/plugin.go#L44

by 
```
        rootURL := ""
	if siteURL := p.API.GetConfig().ServiceSettings.SiteURL; siteURL != nil {
		rootURL = strings.TrimSuffix(*siteURL, "/")
	}
	p.rootURL = fmt.Sprintf("%s/plugins/%s", rootURL, manifest.Manifest.Id)
```

but I can't test it...

**Comment by mickmister** [comment]
@moussetc What's more important than using `nginx` for testing here is using Mattermost with a subpath https://developers.mattermost.com/blog/subpath/#using-subpaths-in-development. That should be enough to test the issue.

**Comment by moussetc** [comment]
@mickmister  Thank you for the link. However I don't use the mattermost-webapp repo to test my plugins, I use the Mattermost Docker preview image, which is why I was trying to go the docker/nginx route. I honestly don't have the motivation to setup the actual Mattermost developer environment (I tried a few years back, lost more than a few hours, didn't manage to get it working and ended up choosing the Docker Preview).

I'll be releasing a new version of the plugin at some point in the future, which will contain the suggested fix above, and hopefully, it'll solve the issue.

Note: seeing as the previous version 2.1.1 is still stuck waiting for review for the official Marketplace publication, I'm not sure that this fix (if it works) will ever get publishedto the Marketplace ,so watch out for Github releases.

**Comment by moussetc** [comment]
The new [2.1.2 release ](https://github.com/moussetc/mattermost-plugin-giphy/releases/tag/v2.1.2) of the plugin now uses the `SiteURL` setting when generating the Giphy attribution picture URL (all other URLs handled by the plugin are Giphy URLs, not impacted by this setting).
